import 'dart:math';

import 'package:tame_yaml/tame_yaml.dart';
import 'package:test/test.dart';

import 'src/helpers.dart';

/// The number of random sources generated by the fuzz test.
const int _iterations = 5000;

/// The maximum number of character codes used to build one random source.
const int _maximumSourceCharacterCodes = 80;

/// Characters that meet at or near a lexical boundary of the grammar.
const List<int> _alphabet = [
  0x00,
  0x09,
  0x0A,
  0x0D,
  0x20,
  0x21,
  0x22,
  0x23,
  0x25,
  0x26,
  0x27,
  0x2A,
  0x2C,
  0x2D,
  0x2E,
  0x30,
  0x39,
  0x3A,
  0x3F,
  0x40,
  0x41,
  0x5B,
  0x5C,
  0x5D,
  0x61,
  0x7B,
  0x7C,
  0x7D,
  0x7E,
  0x85,
  0x2028,
  0x2029,
  0xD800,
  0xDFFF,
  0xFEFF,
  0x1F600,
];

void main() {
  test('answers every random source with data or a YamlException', () {
    // The seed is fixed so that a failure is reproducible.
    final random = Random(0x51A7);

    for (var iteration = 0; iteration < _iterations; iteration += 1) {
      final source = String.fromCharCodes(
        List<int>.generate(
          random.nextInt(_maximumSourceCharacterCodes + 1),
          (_) => _alphabet[random.nextInt(_alphabet.length)],
          growable: false,
        ),
      );

      try {
        final _ = yamlDecodeAll(source);
      } on YamlException {
        // Rejection is expected for most generated sources.
      } on Object catch (error) {
        fail('${describeSource(source)} threw ${error.runtimeType}: $error');
      }
    }
  });
}
