import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:tame_yaml/tame_yaml.dart';

import 'src/yaml_test_suite_data.dart';

const String _outputPath = 'test/src/yaml_test_suite/cases.dart';
const String _usage =
    '''
Usage: dart run tool/generate_yaml_test_suite.dart
       dart run tool/generate_yaml_test_suite.dart --revision=COMMIT

With no arguments, downloads the pinned YAML test suite revision and writes
$_outputPath.
A revision must be a full, lowercase 40-character commit SHA.
''';

/// Generates the vendored, classified YAML test suite corpus.
Future<void> main(List<String> arguments) => runWithYamlTestSuiteData(
  arguments,
  usage: _usage,
  action: (dataDirectory, revision) =>
      _generate(dataDirectory, revision, File(_outputPath)),
);

void _generate(Directory dataDirectory, String revision, File output) {
  final inputs = readYamlTestSuiteInputs(dataDirectory);
  if (inputs.isEmpty) {
    throw YamlTestSuiteDataException(
      'No YAML test suite cases found in ${dataDirectory.path}.',
    );
  }

  final cases = <_GeneratedCase>[];
  for (final input in inputs) {
    final sourceFile = input.source;
    final sourceBytes = sourceFile.readAsBytesSync();
    final source = utf8.decode(sourceBytes);

    final _Classification classification;
    YamlErrorCode? expectedCode;
    if (input.expectsError) {
      classification = _Classification.invalid;
      expectedCode = _decodeError(source, sourceFile.uri);
      if (expectedCode == null) {
        throw YamlTestSuiteDataException(
          'Invalid case was accepted: ${input.id}',
        );
      }
    } else {
      expectedCode = _decodeError(source, sourceFile.uri);
      if (expectedCode == null) {
        classification = _Classification.accepted;
      } else if (_profileErrorCodes.contains(expectedCode)) {
        classification = _Classification.profileRejected;
      } else {
        throw YamlTestSuiteDataException(
          'Valid case failed outside the strict data profile: '
          '${input.id} (${expectedCode.name})',
        );
      }
    }

    final expectedJsonFile = input.expectedJson;
    cases.add((
      id: input.id,
      descriptionBase64: base64Encode(
        utf8.encode(input.description.readAsStringSync().trim()),
      ),
      sourceBase64: base64Encode(sourceBytes),
      expectedJsonBase64: expectedJsonFile.existsSync()
          ? base64Encode(expectedJsonFile.readAsBytesSync())
          : null,
      classification: classification,
      expectedCode: expectedCode,
    ));
  }

  output.parent.createSync(recursive: true);
  output.writeAsStringSync(_render(revision, cases));
  stdout.writeln(
    'Generated ${cases.length} classified cases in ${output.path}.',
  );
}

/// Decodes [source] and reports the error code it fails with, if any.
YamlErrorCode? _decodeError(String source, Uri sourceUrl) {
  try {
    final _ = yamlDecodeAll(source, sourceUrl: sourceUrl);
    return null;
  } on YamlException catch (error) {
    return error.code;
  }
}

/// The codes for valid YAML that the strict data profile rejects by design.
const Set<YamlErrorCode> _profileErrorCodes = {
  .unsupportedVersion,
  .invalidDirective,
  .nonStringKey,
  .duplicateKey,
  .unsupportedFlowEntry,
  .unsupportedTag,
  .invalidTaggedValue,
  .mergeKey,
  .unsupportedAnchorName,
  .undefinedAlias,
  .recursiveAlias,
  .integerOutOfRange,
  .leadingZeroInteger,
  .resourceLimit,
};

enum _Classification {
  accepted,
  profileRejected,
  invalid,
}

typedef _GeneratedCase = ({
  String id,
  String descriptionBase64,
  String sourceBase64,
  String? expectedJsonBase64,
  _Classification classification,
  YamlErrorCode? expectedCode,
});

String _render(String revision, List<_GeneratedCase> cases) {
  final output = StringBuffer('''
// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by tool/generate_yaml_test_suite.dart from
// https://github.com/yaml/yaml-test-suite
// revision $revision.
//
// The vendored inputs, expected JSON, and descriptions below are
// copyright 2016-2020 Ingy döt Net, MIT licensed;
// see the LICENSE file next to this one.

import 'package:tame_yaml/tame_yaml.dart';

/// The pinned YAML test suite revision represented by [yamlTestSuiteCases].
const String yamlTestSuiteRevision = ${_literal(revision)};

/// A reviewed classification for one YAML test suite case.
enum YamlTestSuiteClassification {
  /// Valid YAML accepted by the strict data profile.
  accepted,

  /// Valid YAML intentionally rejected by the strict data profile.
  profileRejected,

  /// Invalid YAML rejected by the decoder.
  invalid,
}

/// One vendored YAML test suite case.
final class YamlTestSuiteCase {
  /// Creates a test case from its generated, encoded data.
  const YamlTestSuiteCase(
    this.id,
    this.descriptionBase64,
    this.sourceBase64,
    this.expectedJsonBase64,
    this.classification,
    this.expectedCode,
  );

  /// The stable upstream case identifier.
  final String id;

  /// The upstream case description encoded as UTF-8 base64.
  final String descriptionBase64;

  /// The exact `in.yaml` bytes encoded as base64.
  final String sourceBase64;

  /// The upstream `in.json` bytes encoded as base64, when supplied.
  final String? expectedJsonBase64;

  /// The reviewed relationship between this case and the strict profile.
  final YamlTestSuiteClassification classification;

  /// The exact expected code for a rejected case.
  final YamlErrorCode? expectedCode;
}

/// All cases in [yamlTestSuiteRevision], in stable identifier order.
const List<YamlTestSuiteCase> yamlTestSuiteCases = [
''');
  for (final testCase in cases) {
    final expectedCode = switch (testCase.expectedCode) {
      final code? => 'YamlErrorCode.${code.name}',
      null => 'null',
    };
    final expectedJson = switch (testCase.expectedJsonBase64) {
      final json? => _literal(json, indent: '        '),
      null => 'null',
    };
    output.writeln('''
  YamlTestSuiteCase(
    ${_literal(testCase.id)},
    ${_literal(testCase.descriptionBase64, indent: '        ')},
    ${_literal(testCase.sourceBase64, indent: '        ')},
    $expectedJson,
    YamlTestSuiteClassification.${testCase.classification.name},
    $expectedCode,
  ),''');
  }
  output.writeln('];');
  return output.toString();
}

/// Renders [value] as a Dart string literal, split into adjacent literals
/// indented by [indent] so generated lines stay within the line length.
String _literal(String value, {String indent = ''}) {
  const maximumChunkLength = 68;
  if (value.isEmpty) return "''";
  final chunks = <String>[];
  for (var start = 0; start < value.length; start += maximumChunkLength) {
    final end = min(start + maximumChunkLength, value.length);
    chunks.add("'${value.substring(start, end)}'");
  }
  return chunks.join('\n$indent');
}
